# Generated by Django 4.2.1 on 2023-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bnkform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('phonenumber', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('district', models.TextField()),
                ('branch', models.TextField()),
                ('accounttype', models.IntegerField()),
                ('materialprovide', models.TextField()),
            ],
        ),
    ]
